apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels: #Optional
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels: #Compulsory
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password  
--- #Separates the 2 Yaml files
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector: #Select pods to forward requests to
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 #Should be same the same as the the container point